trailingComma: es5
semi: true
singleQuote: false
arrowParens: avoid
printWidth: 140

plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - "^[./]"
importOrderParserPlugins:
  - typescript
  - "decorators-legacy"
